### ISSUE TITLE
Check rule submission consistency

### ISSUE THREAD

**Issue by Taskr** [PUNCH-Cyber/YaraGuardian#38]
Large rule files are being reported as parsing rules inconsistently, but parse correctly when split up across multiple files. 

Requesting others who experience similar behavior add their observations to help track down possible root cause.

**Comment by robertsjw** [comment]
I'm noticing similar behavior, trying to track down the cause

**Comment by Taskr** [comment]
Closing as this seems to be no longer an issue:

- There have been no additional reports or observations of this behavior occurring for some time
- Multiple changes and fixes have occurred in both plyara and YaraGuardian since the initial opening of this issue
