### ISSUE TITLE
UploadDirectory: use sub-folder name as source

### ISSUE THREAD

**Issue by dadokkio** [PUNCH-Cyber/YaraGuardian#46]
Hi,
we are using a custom script to download and keep updated yara rules from different github repos.
Each repo is stored in particular sub-folders under the main folder that we want to bulk upload in YaraGuardian with the UploadDirectory command.
The actual options are:

- bulk import everything having a single source option for everything
- import each sub-folder separately

Can be useful to add an option the the command that permit to use sub-folders name as source?

**Comment by Taskr** [comment]
commit **dd6ae27**
